### PR TITLE
Podcast cards

### LINKED ISSUE #238: Create + Style Podcast cards
This can be started after #236 is finished.

This should be a component.  Create the basic layout of the cards according to the Figma file.  Additional styling can be a different ticket.

### PR DESCRIPTION
**Pull request by ermatlock**
This PR creates reusable podcast cards. For now, the component contains a built-in chip component as well, but that can be broken down into a reusable component in the future.

PodcastCards example:

PodcastCards Example

No additional dependencies installed.

Closes #238  - Create + Style Podcast cards

May need to add some more styling to create fully responsive layout.

### CODE REVIEW

**Comment by lauraehiller** [comment]
@ermatlock I can't merge this unfortunately as the deploy is failing.  Seems like there are some issues with the project dependencies

**Comment by ermatlock** [comment]
Strange, I don't believe I added any new dependencies. Perhaps there's a node mismatch?

**Comment by ermatlock** [comment]
When you tested the branch did you have any issues running it?

**Comment by bcantello** [comment]
Issue is stemming from commit: [af08f47](https://github.com/spacelabdev/spacelab-react/pull/269/commits/af08f47ea558a2dc7813f7897f51daa97bc9f4f3)

Packages should never be updated when creating a feature. The package update and the resulting changes to the package.lock file that is included in this PR are causing the problems. The updates to packages should be rolled back and so that there are no changes to the lock file.

**Comment by ermatlock** [comment]
Good to know. In that case I will make sure the packages are rolled back to main and I will add my package lock to gitignore.__Thanks,Eric MatlockMobile Message530.386.1359On Feb 27, 2023, at 9:42 AM, Brandon Cantello ***@***.***> wrote:﻿
Issue is stemming from commit: af08f47
Packages should never be updated when creating a feature. The package update and the resulting changes to the package.lock file that is included in this PR are causing the problems. The updates to packages should be rolled back and so that there are no changes to the lock file.

**Review by lauraehiller — APPROVED** [review]
Looks good, thanks Eric!

**Comment by lauraehiller** [comment]
Yeah, it's giving me this error message.  It says that it's a local error but I don't have any issues spinning up any of the other branches, just podcast-cards.

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.44.2"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:

  C:\Users\Laura\Projects\SpaceLab\spacelab-react\node_modules\webpack (version: 5.75.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "webpack" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\Users\Laura\Projects\SpaceLab\spacelab-react\node_modules\webpack is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls webpack in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed webpack.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

**Pull request merged**
