### PR TITLE
#354 fix project button to remove underline

### PR DESCRIPTION
**Pull request by DrDrewCain**
The !important keyword is used to override any other styles that may be set on the element. In this case, we are overriding the default style of the button, which is to have an underline. So this should solve the issue of removing that underline.

### CODE REVIEW

**Comment by DrDrewCain** [comment]
@lauraehiller I did also notice that hovering over the contact me button does not highlight that button like all the others, is there a reason for this?

**Review by lauraehiller — CHANGES_REQUESTED** [review]
I checked out the deploy preview and I'm still seeing the blue underline on the Explore Exoplanetarium button.  Also, if you look on globalStyles.scss, the default button style should not have an underline.

Thank you for pointing out the contact button on the home page, it's an issue with main, not your branch:)  Someone must've forgotten to nest their styles and I missed it.

**Comment by DrDrewCain** [comment]
> I checked out the deploy preview and I'm still seeing the blue underline on the Explore Exoplanetarium button. Also, if you look on globalStyles.scss, the default button style should not have an underline.
> 
> Thank you for pointing out the contact button on the home page, it's an issue with main, not your branch:) Someone must've forgotten to nest their styles and I missed it.

Huh interesting, I'll take a look at that blue underline again. It must be part of the globalStyles then that needs to be changed.

**Comment by DrDrewCain** [comment]
Huh, I don't see the blue-line when I 

> > I checked out the deploy preview and I'm still seeing the blue underline on the Explore Exoplanetarium button. Also, if you look on globalStyles.scss, the default button style should not have an underline.
> > Thank you for pointing out the contact button on the home page, it's an issue with main, not your branch:) Someone must've forgotten to nest their styles and I missed it.
> 
> Huh interesting, I'll take a look at that blue underline again. I'd imagine that the modified change should happen in project.js where button is 🤔

Got it. It's removed.

**Comment by DrDrewCain** [comment]
Solved. 
Screenshot 2023-05-25 at 11 42 02 PM

**Review by lauraehiller — APPROVED** [review]

**Pull request merged**
