### PR TITLE
switching from modal version to true landing page, nesting styles for…

### PR DESCRIPTION
**Pull request by annakreno**
Nested styling, working on switching landing page from modal to true landing page.

### CODE REVIEW

**Review by DrDrewCain — APPROVED** [review]
Looks pretty clean.

**Review by lauraehiller — CHANGES_REQUESTED** [review]
Looks good, great work on the button gradient!  Just a few notes:
- Make sure Webpack is compiling without warnings!  You are getting that error because you imported useState in SignUp.js but aren't using it.
- Add alt props to all your images (this is very important for accessibility and SEO)
- Make sure to use const instead of let inside of handleMouseMove(), also make sure to remove the console.log as it will affect the site's performance
- When I spin up this branch locally I am unable to see the subscribe form.  Is the form supposed to show, or are you still working on this?

**Review by DrDrewCain — CHANGES_REQUESTED** [review]
unapproving seems there's been a lot of changes/modifications to the work.

**Comment by DrDrewCain** [comment]
This is just my opinion, no need to think much of it, but I personally think this should be broken into smaller work. It seems like a lot of work has been done in here by various people which is pretty awesome to see.

**Pull request closed without merging**
